release:
  github:
    owner: KeisukeToyota
    name: toyotter
  name_template: '{{.Tag}}'
before:
  hooks:
    - go mod download
brew:
  github:
    owner: KeisukeToyota
    name: homebrew-toyotter
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  description: "CUI based Twitter client for Golang"
  homepage: "https://github.com/KeisukeToyota/toyotter"
  dependencies:
    - fzf
  install: |
    bin.install 'toyotter'
builds:
  - main: main.go
    binary: toyotter
    goos:
      - darwin
      - linux
    goarch:
      - amd64
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
