language: go

go:
  - "1.13.4"
env:
 - GO111MODULE=on

install:
 - go mod download
 - go get -u github.com/goreleaser/goreleaser

after_success:
  - goreleaser

notifications:
  email:
    on_success: never
