language: go

go:
  - "1.13.4"
env:
 - GO111MODULE=on

install:
 - go mod download
 - go get -u github.com/goreleaser/goreleaser

notifications:
  email:
    on_success: never

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
