language: go

go:
  - "1.11.4"
env:
 - GO111MODULE=on

install:
 - go mod download

deploy:
- provider: script
  skip_cleanup: true
  script: bash goreleaser.sh
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux

notifications:
  email:
    on_success: never
