language: go
go:
  - "1.11"
install:
 - go get -u golang.org/x/tools/cmd/goimports
 - go get -u github.com/golang/lint/golint
 - go get -u github.com/goreleaser/goreleaser

script:
 - env GO111MODULE=on go vet ./...
 - diff <(env GO111MODULE=on goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*")) <(printf "")
 - diff <(env GO111MODULE=on go list ./... | xargs -L1 golint -set_exit_status) <(printf "")

after_success:
 - goreleaser
