language: go
go:
  - "1.11.4"
env:
 - GO111MODULE=on
install:
 - go mod download
 - go get -u golang.org/x/tools/cmd/goimports
 - go get -u golang.org/x/lint/golint
 - go get -u github.com/goreleaser/goreleaser
script:
 - go vet ./...
 - diff <(goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*")) <(printf "")
 - diff <(go list ./... | xargs -L1 golint -set_exit_status) <(printf "")

after_success:
 - goreleaser
